defaults:
  - chain: translate_ger_to_eng
  - embedding: rewe_fdc_embedding

data:
  input_path: data/processed/merged_rewe_fdc_insulin.csv
  input_column: Non Nutrient Data.FDC Name
  output_path: data/final/merged_rewe_fdc_insulin_time.csv
  output_column: Non Nutrient Data.Preparation Time


hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: false

mlflow:
  experiment_name: "hydra_mlflow"
  run_name: "test_run"
  tracking_uri: "mlruns"