defaults:
  - prompt: extract_regulated_food_name
  - model: default
  - response_schema: extract_regulated_food_name
  
type: data_processing
input_type: string # string, dict, message, chat_history_to_str, last_chat_message_str_from_chat
output_parser: JsonOutputToolsParser