defaults:
  - prompt: match_food_names
  - model: default
  - response_schema: match_food_names
  
type: data_processing
input_type: string # string, dict, message, chat_history_to_str, last_chat_message_str_from_chat
output_parser: JsonOutputToolsParser