defaults:
  - prompt: translate_ger_to_eng
  - model: default
  - response_schema: translate_ger_to_eng
  
type: data_processing
input_type: string # string, dict, message, chat_history_to_str, last_chat_message_str_from_chat
output_parser: JsonOutputToolsParser